# Generated by Django 4.0.1 on 2022-02-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource', models.CharField(max_length=200)),
                ('univercity', models.CharField(max_length=200)),
                ('classs', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('document', models.ImageField(upload_to='')),
            ],
        ),
    ]
